spec:
  template:
    metadata:
      annotations:
        oneagent.dynatrace.com/inject: "true"
        metadata.dynatrace.com/process.technology: ".NET" 
    spec:
      containers:
        - name: cartservice
          image: ghcr.io/open-telemetry/demo:1.12.0-cartservice
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi  # Original 120Mi - https://docs.dynatrace.com/docs/setup-and-configuration/dynatrace-oneagent/memory-requirements
          env:
            - name: Logging__LogLevel__Default  # https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0
              value: "Debug"
            - name: Logging__LogLevel__Microsoft
              value: "Information"
            - name: Logging__LogLevel__Microsoft.AspNetCore
              value: "Information"
            - name: Logging__LogLevel__Microsoft.AspNetCore.Mvc
              value: "Warning"
            - name: Logging__LogLevel__Microsoft.AspNetCore.Routing
              value: "Warning"
            - name: Logging__LogLevel__Microsoft.Hosting.Lifetime
              value: "Warning"
            - name: Logging__LogLevel__Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware
              value: "Information"
            - name: DT_LOGLEVELCON # https://www.dynatrace.com/support/help/shortlink/agent-logging
              value: "" # info
            - name: DT_LOGCON_PROC
              value: "" # stdout
            - name: DT_LOGGING_DESTINATION
              value: "" # stdout 
            - name: DT_LOGGING_DOTNET_FLAGS
              value: '' # Exporter=true,SpanProcessor=true,Propagator=true,Core=true
            - name: OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED
              value: 'false' # Avoid duplicate spans from OA and Otel -  https://opentelemetry.io/docs/zero-code/net/instrumentations/
            - name: OTEL_COLLECTOR_NAME
              value: 'dynatrace-otel-gateway-collector'
            - name: OTEL_TRACES_EXPORTER
              value: 'none' # 'console', 'none', 'otlp'
            - name: OTEL_LOGS_EXPORTER
              value: 'none' # 'console', 'none', 'otlp'
            - name: OTEL_METRICS_EXPORTER
              value: 'console,otlp' # 'console', 'none', 'otlp'